//------------------------------------------------------------------------
// Project     : VST SDK
// Version     : 3.1.0
//
// Category    : Examples
// Filename    : public.sdk/samples/vst/again/source/version.h
// Created by  : Steinberg, 01/2008
// Description : Example of handle the versionning and copyright info of again plugin 
//				 used for the resources (RC file for example)
//
//-----------------------------------------------------------------------------
// LICENSE
// (c) 2010, Steinberg Media Technologies GmbH, All Rights Reserved
//-----------------------------------------------------------------------------
// This Software Development Kit may not be distributed in parts or its entirety  
// without prior written agreement by Steinberg Media Technologies GmbH. 
// This SDK must not be used to re-engineer or manipulate any technology used  
// in any Steinberg or Third-party application or software module, 
// unless permitted by law.
// Neither the name of the Steinberg Media Technologies nor the names of its
// contributors may be used to endorse or promote products derived from this 
// software without specific prior written permission.
// 
// THIS SDK IS PROVIDED BY STEINBERG MEDIA TECHNOLOGIES GMBH "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL STEINBERG MEDIA TECHNOLOGIES GMBH BE LIABLE FOR ANY DIRECT, 
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
// OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
// OF THE POSSIBILITY OF SUCH DAMAGE.
//-----------------------------------------------------------------------------

#pragma once

// Plain project version file generated by cmake
#include "projectversion.h"
//#include "pluginterfaces/base/fplatform.h"

// #define MAJOR_VERSION_STR "2"
// #define MAJOR_VERSION_INT 2

// #define SUB_VERSION_STR "2"
// #define SUB_VERSION_INT 2

// #define RELEASE_NUMBER_STR "0"
// #define RELEASE_NUMBER_INT 0

// #define BUILD_NUMBER_STR "0" // Build number to be sure that each result could identified.
// #define BUILD_NUMBER_INT 0

// // Version with build number (example "1.0.3.342")
// #define FULL_VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR "." BUILD_NUMBER_STR

// // Version without build number (example "1.0.3")
// #define VERSION_STR MAJOR_VERSION_STR "." SUB_VERSION_STR "." RELEASE_NUMBER_STR

//#define stringOriginalFilename	"VinylSampler20.vst3"
#define stringPluginName 		"Vinyl Sampler 2"

#if PLATFORM_64
#define stringFileDescription	"VinylSampler VST3-SDK (64Bit)"
#else
#define stringFileDescription	"VinylSampler VST3-SDK"
#endif
#define stringCompanyName		"BassBuster\0"
#define stringLegalCopyright	"(c) 2011 BassBuster"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"

